name: Deploy GitHub Pages

# Trigger on push to main
on:
  push:
    branches:
      - main  # Change if your default branch is different

# Permissions
permissions:
  contents: write  # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      # 2️⃣ (Optional) Build step if you have one
      # If you just have index.html + JS, this can be skipped
      - name: Build
        run: echo "No build step needed"

      # 3️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Make sure this folder contains your index.html
