name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # change to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout your repo without submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      # 2️⃣ (Optional) Build your site if needed
      - name: Build
        run: echo "No build step needed"

      # 3️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Change if your site is in a subfolder

